# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e8a0b9ddc63ad2b92133603668007cd6826226d1accdbe30dad4c13f578ca52c3e4ee1e36e9686dae19df5b8b97aeede38acf43d0ff17bcf0135baf1ea9b82e

test:
  secret_key_base: df0d0cbc07182c79857223727f449c2a637797b02122ed6454bca3eff7e5bb18b89b3c8b38ef09765d449a80e6a22299035f3bcd4307fc4f4989dde90f995b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
